events { worker_connections 4096; }
http {
  resolver 127.0.0.11 valid=5s;
  server {
    listen 3000;
    location / {
      set $backend api;
      proxy_pass http://$backend:3010;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }
  }
}
