events { worker_connections 4096; }
http {
  upstream api_servers {
    server host.docker.internal:3010;
    server host.docker.internal:3011;
    server host.docker.internal:3012;
    server host.docker.internal:3013;
    server host.docker.internal:3014;
    server host.docker.internal:3015;
    server host.docker.internal:3016;
    server host.docker.internal:3017;
    keepalive 128;
  }
  server {
    listen 3000;
    location / {
      proxy_pass http://api_servers;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }
  }
}
